# Generated by Django 5.1.3 on 2025-01-03 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_showtime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='showtime',
            old_name='show_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='showtime',
            old_name='show_time',
            new_name='time',
        ),
        migrations.AddField(
            model_name='showtime',
            name='theater',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movies.theater'),
        ),
    ]
