# Generated by Django 5.1.3 on 2025-01-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_rename_show_date_showtime_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
    ]
