# Generated by Django 5.1.3 on 2025-01-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_booking_ticket_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('event_date', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('concert', 'Concert'), ('sports', 'Sports'), ('theater', 'Theater'), ('festival', 'Festival'), ('opera', 'Opera')], max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
