# Generated by Django 5.1.3 on 2025-01-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_liveevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='highlighted',
            field=models.BooleanField(default=False),
        ),
    ]
